import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Agregar Producto");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setText("Buscar Producto");
        jButton10.addActionListener(this::jButton10ActionPerformed);

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setText("Eliminar Producto");
        jButton11.addActionListener(this::jButton11ActionPerformed);

        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton12.setText("Registrar Venta");
        jButton12.addActionListener(this::jButton12ActionPerformed);

        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton13.setText("Generar Reporte");
        jButton13.addActionListener(this::jButton13ActionPerformed);

        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton14.setText("Ver Datos");
        jButton14.addActionListener(this::jButton14ActionPerformed);

        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton15.setText("Salir");
        jButton15.addActionListener(this::jButton15ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setText("Megapaca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mostrarVentanaAgregar();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        mostrarVentanaBuscar();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        mostrarVentanaEliminar();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        mostrarVentanaVenta();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        mostrarVentanaReportes();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        mostrarDatosEstudiante();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
private Inventario inventario = new Inventario();

//----- Agregar Producto -----
    private void mostrarVentanaAgregar() {
        JDialog dialogo = new JDialog(this, "Agregar Producto", true);
        dialogo.setSize(400, 350);
        dialogo.setLocationRelativeTo(this);
        dialogo.setLayout(new GridLayout(7, 2, 10, 10));
        dialogo.getRootPane().setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        JLabel lblCodigo = new JLabel("Codigo:");
        JTextField txtCodigo = new JTextField();
        JLabel lblNombre = new JLabel("Nombre:");
        JTextField txtNombre = new JTextField();
        JLabel lblCategoria = new JLabel("Categoria:");
        JTextField txtCategoria = new JTextField();
        JLabel lblPrecio = new JLabel("Precio:");
        JTextField txtPrecio = new JTextField();
        JLabel lblStock = new JLabel("Stock:");
        JTextField txtStock = new JTextField();
        JButton btnGuardar = new JButton("Guardar");
        JButton btnCancelar = new JButton("Cancelar");
        
        dialogo.add(lblCodigo); dialogo.add(txtCodigo);
        dialogo.add(lblNombre); dialogo.add(txtNombre);
        dialogo.add(lblCategoria); dialogo.add(txtCategoria);
        dialogo.add(lblPrecio); dialogo.add(txtPrecio);
        dialogo.add(lblStock); dialogo.add(txtStock);
        dialogo.add(btnGuardar); dialogo.add(btnCancelar);
        
        btnGuardar.addActionListener(e -> {
            try {
                String codigo = txtCodigo.getText().trim();
                String nombre = txtNombre.getText().trim();
                String categoria = txtCategoria.getText().trim();

                if (codigo.isEmpty() || nombre.isEmpty() || categoria.isEmpty()) {
                    JOptionPane.showMessageDialog(dialogo, "Todos los campos son obligatorios");
                    return;
                }
                double precio = Double.parseDouble(txtPrecio.getText().trim());
                int stock = Integer.parseInt(txtStock.getText().trim());
                String resultado = inventario.agregarProducto(codigo, nombre, categoria, precio, stock);
                JOptionPane.showMessageDialog(dialogo, resultado);
                if (resultado.contains("correctamente")) {
                    dialogo.dispose();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialogo, "Precio y stock deben ser valores numericos");
            }
        });
        btnCancelar.addActionListener(e -> dialogo.dispose());
        dialogo.setVisible(true);
    }

    //----- Buscar Producto -----
    private void mostrarVentanaBuscar() {
        JDialog dialogo = new JDialog(this, "Buscar Producto", true);
        dialogo.setSize(700, 400);
        dialogo.setLocationRelativeTo(this);
        dialogo.setLayout(new BorderLayout(10, 10));
        JPanel panelBusqueda = new JPanel(new FlowLayout());
        JLabel lblBuscar = new JLabel("Buscar por nombre, codigo o categoria:");
        JTextField txtBuscar = new JTextField(20);
        JButton btnBuscar = new JButton("Buscar");
        panelBusqueda.add(lblBuscar);
        panelBusqueda.add(txtBuscar);
        panelBusqueda.add(btnBuscar);
        String[] columnas = {"Codigo", "Nombre", "Categoria", "Precio", "Stock"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
        JTable tabla = new JTable(modelo);
        JScrollPane scroll = new JScrollPane(tabla);
        JButton btnCerrar = new JButton("Cerrar");
        JPanel panelBoton = new JPanel();
        panelBoton.add(btnCerrar);
        dialogo.add(panelBusqueda, BorderLayout.NORTH);
        dialogo.add(scroll, BorderLayout.CENTER);
        dialogo.add(panelBoton, BorderLayout.SOUTH);
        
        btnBuscar.addActionListener(e -> {
            modelo.setRowCount(0);
            String criterio = txtBuscar.getText().trim();
            if (criterio.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "Ingresa un criterio de busqueda");
                return;
            }
            Producto[] resultados = inventario.buscarProducto(criterio);
            if (resultados.length == 0) {
                JOptionPane.showMessageDialog(dialogo, "No se encontraron productos");
            } else {
                for (Producto p : resultados) {
                    modelo.addRow(new Object[]{p.getCodigo(), p.getNombre(), p.getCategoria(), "Q" + p.getPrecio(), p.getStock()});
                }
            }
        });
        
        btnCerrar.addActionListener(e -> dialogo.dispose());
        dialogo.setVisible(true);
    }

    //----- Eliminar Producto -----
    private void mostrarVentanaEliminar() {
        JDialog dialogo = new JDialog(this, "Eliminar Producto", true);
        dialogo.setSize(350, 200);
        dialogo.setLocationRelativeTo(this);
        dialogo.setLayout(new GridLayout(3, 2, 10, 10));
        dialogo.getRootPane().setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        JLabel lblCodigo = new JLabel("Codigo del producto:");
        JTextField txtCodigo = new JTextField();
        JButton btnEliminar = new JButton("Eliminar");
        JButton btnCancelar = new JButton("Cancelar");
        dialogo.add(lblCodigo); dialogo.add(txtCodigo);
        dialogo.add(btnEliminar); dialogo.add(btnCancelar);
        
        btnEliminar.addActionListener(e -> {
            String codigo = txtCodigo.getText().trim();
            if (codigo.isEmpty()) {
                JOptionPane.showMessageDialog(dialogo, "Ingresa el codigo del producto");
                return;
            }
            int confirmacion = JOptionPane.showConfirmDialog(dialogo,
                "¿Estas seguro de eliminar el producto con codigo: " + codigo + "?",
                "Confirmacion", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                String resultado = inventario.eliminarProducto(codigo);
                JOptionPane.showMessageDialog(dialogo, resultado);
                if (resultado.contains("correctamente")) {
                    dialogo.dispose();
                }
            }
        });
        
        btnCancelar.addActionListener(e -> dialogo.dispose());
        dialogo.setVisible(true);
    }
    
    //----- Registrar Venta -----
    private void mostrarVentanaVenta() {
        JDialog dialogo = new JDialog(this, "Registrar Venta", true);
        dialogo.setSize(350, 230);
        dialogo.setLocationRelativeTo(this);
        dialogo.setLayout(new GridLayout(4, 2, 10, 10));
        dialogo.getRootPane().setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        JLabel lblCodigo = new JLabel("Codigo del producto:");
        JTextField txtCodigo = new JTextField();
        JLabel lblCantidad = new JLabel("Cantidad:");
        JTextField txtCantidad = new JTextField();
        JButton btnVender = new JButton("Registrar Venta");
        JButton btnCancelar = new JButton("Cancelar");
        dialogo.add(lblCodigo); dialogo.add(txtCodigo);
        dialogo.add(lblCantidad); dialogo.add(txtCantidad);
        dialogo.add(btnVender); dialogo.add(btnCancelar);
        
        btnVender.addActionListener(e -> {
            try {
                String codigo = txtCodigo.getText().trim();
                if (codigo.isEmpty()) {
                    JOptionPane.showMessageDialog(dialogo, "Ingresa el codigo del producto.");
                    return;
                }
                int cantidad = Integer.parseInt(txtCantidad.getText().trim());
                String resultado = inventario.registrarVenta(codigo, cantidad);
                JOptionPane.showMessageDialog(dialogo, resultado);
                if (resultado.contains("correctamente")) {
                    dialogo.dispose();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialogo, "La cantidad debe ser un numero entero.");
            }
        });

        btnCancelar.addActionListener(e -> dialogo.dispose());
        dialogo.setVisible(true);
    }
    
    //------ Reportes ------
    private void mostrarVentanaReportes() {
        JDialog dialogo = new JDialog(this, "Generar Reportes", true);
        dialogo.setSize(350, 200);
        dialogo.setLocationRelativeTo(this);
        dialogo.setLayout(new GridLayout(3, 1, 10, 10));
        dialogo.getRootPane().setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        JButton btnStock = new JButton("Generar Reporte de Stock");
        JButton btnVentas = new JButton("Generar Reporte de Ventas");
        JButton btnCerrar = new JButton("Cerrar");

        dialogo.add(btnStock);
        dialogo.add(btnVentas);
        dialogo.add(btnCerrar);

        btnStock.addActionListener(e -> {
            String resultado = inventario.generarReporteStock();
            JOptionPane.showMessageDialog(dialogo, resultado);
        });

        btnVentas.addActionListener(e -> {
            String resultado = inventario.generarReporteVentas();
            JOptionPane.showMessageDialog(dialogo, resultado);
        });

        btnCerrar.addActionListener(e -> dialogo.dispose());
        dialogo.setVisible(true);
    }
    
    //----- Datos Personales -----
    private void mostrarDatosEstudiante() {
        JOptionPane.showMessageDialog(this,
            "Nombre: Juan Jacobo Diaz Naola\n" +
            "Carnet: 202408106\n" +
            "Curso: LAB de Introduccion a la Programacion y Computacion 1\n" +
            "Seccion: B\n" +
            "Universidad de San Carlos de Guatemala",
            "Datos del Estudiante",
            JOptionPane.INFORMATION_MESSAGE);
    }
}
